[package]
name = "n8iv_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }    # Async operations
serde = { version = "1.0", features = ["derive"] }  # Serialization/deserialization
serde_json = "1.0"                                  # JSON parsing
sha2 = "0.9"                                        # SHA-256 for hashing
rand = "0.8"                                        # Random number generation
hyper = { version = "0.14", features = ["full"] }   # HTTP client/server
futures = "0.3"                                     # Async futures handling
curve25519-dalek = "3.0"                            # Cryptography for Curve25519
ed25519-dalek = "1.0"                               # Ed25519 signature scheme
